server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chanel?serverTimeZone=GMT-8
    username: root
    password: yankai
    driver-class-name: com.mysql.cj.jdbc.Driver
  web:
    resources:
      static-locations:
        - classpath:/static
        - file:./static
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true

